export default {
    REQUEST_HANDSHAKE: 'REQUEST_HANDSHAKE',
    REQUEST_CREATE_NEW_ACCOUNT: 'REQUEST_CREATE_NEW_ACCOUNT',
     //get booking deatails
    REQUEST_GET_CUST_BOOKING_DETAILS:'REQUEST_GET_CUST_BOOKING_DETAILS',
    //POST THE QOUTES
    REQUEST_POST_VENDOR_QUOTES_DETAILS:'REQUEST_POST_VENDOR_QUOTES_DETAILS'
    
}
