export default {
    REQUEST_HANDSHAKE: 'REQUEST_HANDSHAKE',
    TOLL_ROUTE_DATA: 'TOLL_ROUTE_DATA',
    REQUEST_CREATE_NEW_ACCOUNT: 'REQUEST_CREATE_NEW_ACCOUNT',
    REQUEST_VALIDATE_OTP: 'REQUEST_VALIDATE_OTP',
    REQUEST_DASHBOARD_ON_LOAD: 'REQUEST_DASHBOARD_ON_LOAD',
    NEW_BOOKING_CONFIRMATION: 'NEW_BOOKING_CONFIRMATION',
    REQUEST_GET_DRIVER_DETAILS_BY_ID: 'REQUEST_GET_DRIVER_DETAILS',
    
    // REQUEST_BOOKING_LEVEL_ONE: 'REQUEST_BOOKING_LEVEL_ONE',
    // REQUEST_BOOKING_LEVEL_TWO: 'REQUEST_BOOKING_LEVEL_TWO',
    REQUEST_GET_QUOTE_DETAILS_BY_BOOKINGID: 'REQUEST_GET_QUOTE_DETAILS_BY_BOOKINGID',
    REQUEST_GET_LIST_OF_BOOKINGS_BY_PHONE_NO: 'REQUEST_GET_LIST_OF_BOOKINGS_BY_PHONE_NO',

    REQUEST_GET_VENDOR_FEEDBACK_BY_VENDORID:'REQUEST_GET_VENDOR_FEEDBACK_BY_VENDORID',
}
